In [1]:
!pip install Pillow

In [2]:
!pip install tensorflow
!pip install keras

In [3]:
!pip install scikeras
!pip install opencv-python

In [4]:
import pandas as pd
import os
from skimage.transform import resize
from skimage.io import imread
import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from PIL import Image
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping
from scikeras.wrappers import KerasClassifier
import cv2

In [ ]:
data = []
labels = []

data_dir = '/content/drive/MyDrive/Hybrid Animals'
beefalos = os.path.join(data_dir, 'beefalo')
for beefalo in os.listdir(beefalos):

  img_path = os.path.join(beefalos, beefalo)
  print(img_path)
  if not img_path.lower().endswith(('.png', '.jpg', '.jpeg')) or os.path.getsize(img_path) == 0:
            print(f"Skipping non-image file or file with size 0: {img_path}")
            continue
  imag = cv2.imread(img_path)
  if imag is None:
    continue
  img_from_ar = Image.fromarray(imag, 'RGB')
  resized_image = img_from_ar.resize((50, 50))
  data.append(np.array(resized_image))
  labels.append(0)


coywolves = os.path.join(data_dir, 'coywolf')
for coywolf in os.listdir(coywolves):

  img_path = os.path.join(coywolves, coywolf)
  print(img_path)
  if not img_path.lower().endswith(('.png', '.jpg', '.jpeg')) or os.path.getsize(img_path) == 0:
            print(f"Skipping non-image file or file with size 0: {img_path}")
            continue
  imag = cv2.imread(img_path)
  if imag is None:
    continue
  img_from_ar = Image.fromarray(imag, 'RGB')
  resized_image = img_from_ar.resize((50, 50))
  data.append(np.array(resized_image))
  labels.append(1)


geeps = os.path.join(data_dir, 'geep')
for geep in os.listdir(geeps):

  img_path = os.path.join(geeps, geep)
  print(img_path)
  if not img_path.lower().endswith(('.png', '.jpg', '.jpeg')) or os.path.getsize(img_path) == 0:
            print(f"Skipping non-image file or file with size 0: {img_path}")
            continue
  imag = cv2.imread(img_path)
  if imag is None:
    continue
  img_from_ar = Image.fromarray(imag, 'RGB')
  resized_image = img_from_ar.resize((50, 50))
  data.append(np.array(resized_image))
  labels.append(2)


ligers = os.path.join(data_dir, 'liger')
for liger in os.listdir(ligers):

  img_path = os.path.join(ligers, liger)
  print(img_path)
  if not img_path.lower().endswith(('.png', '.jpg', '.jpeg')) or os.path.getsize(img_path) == 0:
            print(f"Skipping non-image file or file with size 0: {img_path}")
            continue
  imag = cv2.imread(img_path)
  if imag is None:
    continue
  img_from_ar = Image.fromarray(imag, 'RGB')
  resized_image = img_from_ar.resize((50, 50))
  data.append(np.array(resized_image))
  labels.append(3)


mules = os.path.join(data_dir, 'mule')
for mule in os.listdir(mules):

  img_path = os.path.join(mules, mule)
  print(img_path)
  if not img_path.lower().endswith(('.png', '.jpg', '.jpeg')) or os.path.getsize(img_path) == 0:
            print(f"Skipping non-image file or file with size 0: {img_path}")
            continue
  imag = cv2.imread(img_path)
  if imag is None:
    continue
  img_from_ar = Image.fromarray(imag, 'RGB')
  resized_image = img_from_ar.resize((50, 50))
  data.append(np.array(resized_image))
  labels.append(4)


ocicats = os.path.join(data_dir, 'ocicat')
for ocicat in os.listdir(ocicats):

  img_path = os.path.join(ocicats, ocicat)
  print(img_path)
  if not img_path.lower().endswith(('.png', '.jpg', '.jpeg')) or os.path.getsize(img_path) == 0:
            print(f"Skipping non-image file or file with size 0: {img_path}")
            continue
  imag = cv2.imread(img_path)
  if imag is None:
    continue
  img_from_ar = Image.fromarray(imag, 'RGB')
  resized_image = img_from_ar.resize((50, 50))
  data.append(np.array(resized_image))
  labels.append(5)


pizzlies = os.path.join(data_dir, 'pizzly')
for pizzly in os.listdir(pizzlies):

  img_path = os.path.join(pizzlies, pizzly)
  print(img_path)
  if not img_path.lower().endswith(('.png', '.jpg', '.jpeg')) or os.path.getsize(img_path) == 0:
            print(f"Skipping non-image file or file with size 0: {img_path}")
            continue
  imag = cv2.imread(img_path)
  if imag is None:
    continue
  img_from_ar = Image.fromarray(imag, 'RGB')
  resized_image = img_from_ar.resize((50, 50))
  data.append(np.array(resized_image))
  labels.append(6)


pumapards = os.path.join(data_dir, 'pumapard')
for pumapard in os.listdir(pumapards):

  img_path = os.path.join(pumapards, pumapard)
  print(img_path)
  if not img_path.lower().endswith(('.png', '.jpg', '.jpeg')) or os.path.getsize(img_path) == 0:
            print(f"Skipping non-image file or file with size 0: {img_path}")
            continue
  imag = cv2.imread(img_path)
  if imag is None:
    continue
  img_from_ar = Image.fromarray(imag, 'RGB')
  resized_image = img_from_ar.resize((50, 50))
  data.append(np.array(resized_image))
  labels.append(7)


snow_capped_manakins = os.path.join(data_dir, 'snow capped manakin')
for snow_capped_manakin in os.listdir(snow_capped_manakins):

  img_path = os.path.join(snow_capped_manakins, snow_capped_manakin)
  print(img_path)
  if not img_path.lower().endswith(('.png', '.jpg', '.jpeg')) or os.path.getsize(img_path) == 0:
            print(f"Skipping non-image file or file with size 0: {img_path}")
            continue
  imag = cv2.imread(img_path)
  if imag is None:
    continue
  img_from_ar = Image.fromarray(imag, 'RGB')
  resized_image = img_from_ar.resize((50, 50))
  data.append(np.array(resized_image))
  labels.append(8)


welsh_corgis = os.path.join(data_dir, 'welsh corgi')
for welsh_corgi in os.listdir(welsh_corgis):

  img_path = os.path.join(welsh_corgis, welsh_corgi)
  print(img_path)
  if not img_path.lower().endswith(('.png', '.jpg', '.jpeg')) or os.path.getsize(img_path) == 0:
            print(f"Skipping non-image file or file with size 0: {img_path}")
            continue
  imag = cv2.imread(img_path)
  if imag is None:
    continue
  img_from_ar = Image.fromarray(imag, 'RGB')
  resized_image = img_from_ar.resize((50, 50))
  data.append(np.array(resized_image))
  labels.append(9)


wholphins = os.path.join(data_dir, 'wholphin')
for wholphin in os.listdir(wholphins):

  img_path = os.path.join(wholphins, wholphin)
  print(img_path)
  if not img_path.lower().endswith(('.png', '.jpg', '.jpeg')) or os.path.getsize(img_path) == 0:
            print(f"Skipping non-image file or file with size 0: {img_path}")
            continue
  imag = cv2.imread(img_path)
  if imag is None:
    continue
  img_from_ar = Image.fromarray(imag, 'RGB')
  resized_image = img_from_ar.resize((50, 50))
  data.append(np.array(resized_image))
  labels.append(10)


wolfdogs = os.path.join(data_dir, 'wolfdog')
for wolfdog in os.listdir(wolfdogs):

  img_path = os.path.join(wolfdogs, wolfdog)
  print(img_path)
  if not img_path.lower().endswith(('.png', '.jpg', '.jpeg')) or os.path.getsize(img_path) == 0:
            print(f"Skipping non-image file or file with size 0: {img_path}")
            continue
  imag = cv2.imread(img_path)
  if imag is None:
    continue
  img_from_ar = Image.fromarray(imag, 'RGB')
  resized_image = img_from_ar.resize((50, 50))
  data.append(np.array(resized_image))
  labels.append(11)


zonkies = os.path.join(data_dir, 'zonkey')
for zonkey in os.listdir(zonkies):

  img_path = os.path.join(zonkies, zonkey)
  print(img_path)
  if not img_path.lower().endswith(('.png', '.jpg', '.jpeg')) or os.path.getsize(img_path) == 0:
            print(f"Skipping non-image file or file with size 0: {img_path}")
            continue
  imag = cv2.imread(img_path)
  if imag is None:
    continue
  img_from_ar = Image.fromarray(imag, 'RGB')
  resized_image = img_from_ar.resize((50, 50))
  data.append(np.array(resized_image))
  labels.append(12)

In [6]:
animals = np.array(data)
labels = np.array(labels)

In [7]:
np.save("animals", animals)
np.save("labels", labels)

In [8]:
animals = np.load("/content/animals.npy")
labels = np.load("/content/labels.npy")

In [9]:
s = np.arange(animals.shape[0])
np.random.shuffle(s)
animals=animals[s]
labels = labels[s]

In [10]:
num_classes = len(np.unique(labels))
data_length = len(animals)

In [11]:
(x_train,x_test)=animals[(int)(0.1*data_length):],animals[:(int)(0.1*data_length)]
x_train = x_train.astype('float32')/255
x_test = x_test.astype('float32')/255
train_length=len(x_train)
test_length=len(x_test)
(y_train,y_test)=labels[(int)(0.1*data_length):],labels[:(int)(0.1*data_length)]

In [12]:
import keras
from keras.utils import to_categorical

y_train=keras.utils.to_categorical(y_train,num_classes)
y_test=keras.utils.to_categorical(y_test,num_classes)

In [13]:
from keras.models import Sequential
from keras.layers import Conv2D,MaxPooling2D,Dense,Flatten,Dropout

model=Sequential()
model.add(Conv2D(filters=16,kernel_size=2,padding="same",activation="relu",input_shape=(50,50,3)))
model.add(MaxPooling2D(pool_size=2))
model.add(Conv2D(filters=32,kernel_size=2,padding="same",activation="relu"))
model.add(MaxPooling2D(pool_size=2))
model.add(Conv2D(filters=64,kernel_size=2,padding="same",activation="relu"))
model.add(MaxPooling2D(pool_size=2))
model.add(Dropout(0.2))
model.add(Flatten())
model.add(Dense(500,activation="relu"))
model.add(Dropout(0.2))
model.add(Dense(13,activation="softmax"))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 50, 50, 16)        208       
                                                                 
 max_pooling2d (MaxPooling2  (None, 25, 25, 16)        0         
 D)                                                              
                                                                 
 conv2d_1 (Conv2D)           (None, 25, 25, 32)        2080      
                                                                 
 max_pooling2d_1 (MaxPoolin  (None, 12, 12, 32)        0         
 g2D)                                                            
                                                                 
 conv2d_2 (Conv2D)           (None, 12, 12, 64)        8256      
                                                                 
 max_pooling2d_2 (MaxPoolin  (None, 6, 6, 64)          0

In [14]:
model.compile(loss='categorical_crossentropy', optimizer='adam',
                  metrics=['accuracy'])


In [15]:
history = model.fit(x_train,y_train,batch_size=50
          ,epochs=100,verbose=1)

Epoch 1/100
72/72 [==============================] - 7s 9ms/step - loss: 2.3184 - accuracy: 0.2147
Epoch 2/100
72/72 [==============================] - 0s 5ms/step - loss: 1.9524 - accuracy: 0.3532
Epoch 3/100
72/72 [==============================] - 0s 5ms/step - loss: 1.7045 - accuracy: 0.4472
Epoch 4/100
72/72 [==============================] - 0s 5ms/step - loss: 1.5541 - accuracy: 0.4992
Epoch 5/100
72/72 [==============================] - 0s 5ms/step - loss: 1.3883 - accuracy: 0.5617
Epoch 6/100
72/72 [==============================] - 0s 5ms/step - loss: 1.2839 - accuracy: 0.5955
Epoch 7/100
72/72 [==============================] - 0s 5ms/step - loss: 1.1537 - accuracy: 0.6441
Epoch 8/100
72/72 [==============================] - 0s 5ms/step - loss: 1.0421 - accuracy: 0.6767
Epoch 9/100
72/72 [==============================] - 0s 5ms/step - loss: 0.9179 - accuracy: 0.7085
Epoch 10/100
72/72 [==============================] - 0s 5ms/step - loss: 0.8260 - accuracy: 0.7418
Epoch 11/

In [16]:
from sklearn.metrics import confusion_matrix, classification_report

In [19]:
y_true = np.argmax(y_test, axis=1)

# Assuming model.predict returns probabilities
y_pred_probs = model.predict(x_test)
y_pred = np.argmax(y_pred_probs, axis=1)

# Generate confusion matrix
conf_matrix = confusion_matrix(y_true, y_pred)

# Generate classification report
report = classification_report(y_true, y_pred)

print("Confusion Matrix:")
print(conf_matrix)
print("\nClassification Report:")
print(report)

13/13 [==============================] - 0s 4ms/step
Confusion Matrix:
[[16  0  0  1  2  0  1  0  2  0  0  0  2]
 [ 0 17  0  1  1  0  0  1  1  0  0  2  0]
 [ 0  0  8  0  0  0  0  0  0  1  0  1  1]
 [ 0  1  1 13  0  1  1  4  1  0  0  2  1]
 [ 4  0  0  3  6  2  0  1  0  0  0  1  4]
 [ 1  3  0  0  1 26  1  5  4  1  3  1  1]
 [ 2  0  0  0  0  1 17  1  2  2  0  1  1]
 [ 1  3  0  2  1  0  3 21  5  0  0  0  5]
 [ 0  1  1  0  1  0  0  0 29  0  0  0  0]
 [ 2  3  0  3  0  2  0  0  3 39  1  2  0]
 [ 1  0  0  0  0  1  0  1  1  0 24  1  0]
 [ 1  2  1  0  2  0  1  1  2  2  1 20  2]
 [ 1  2  1  1  0  1  0  0  0  1  0  0 21]]

Classification Report:
              precision    recall  f1-score   support

           0       0.55      0.67      0.60        24
           1       0.53      0.74      0.62        23
           2       0.67      0.73      0.70        11
           3       0.54      0.52      0.53        25
           4       0.43      0.29      0.34        21
           5       0.76      0.55

In [20]:
score = model.evaluate(x_test, y_test, verbose=1)
print('\n', 'Test accuracy:', score[1])

13/13 [==============================] - 0s 5ms/step - loss: 2.5253 - accuracy: 0.6457

 Test accuracy: 0.6457286477088928


In [21]:
def convert_to_array(img):
    im = cv2.imread(img)
    img = Image.fromarray(im, 'RGB')
    image = img.resize((50, 50))
    return np.array(image)
def get_animal_name(label):
    if label==0:
        return "beefalo"
    if label==1:
        return "coywolf"
    if label==2:
        return "geep"
    if label==3:
        return "liger"
    if label==4:
        return "mule"
    if label==5:
        return "ocicat"
    if label==6:
        return "pizzly"
    if label==7:
        return "pumapard"
    if label==8:
        return "snow capped manakin"
    if label==9:
        return "welsh corgi"
    if label==10:
        return "wholphin"
    if label==11:
        return "wolfdog"
    if label == 12:
        return "zonkey"
def predict_animal(file):
    print("Predicting .................................")
    ar=convert_to_array(file)
    ar=ar/255
    label=1
    a=[]
    a.append(ar)
    a=np.array(a)
    score=model.predict(a,verbose=1)
    print(score)
    label_index=np.argmax(score)
    print(label_index)
    acc=np.max(score)
    animal=get_animal_name(label_index)
    print(animal)
    print("The predicted Animal is a "+animal+" with accuracy =    "+str(acc))

In [22]:
predict_animal("/content/drive/MyDrive/Hybrid Animals/liger/th-1031154384.jpeg")

Predicting .................................
1/1 [==============================] - 0s 234ms/step
[[7.6024690e-14 2.2075901e-09 3.0372931e-16 9.9999392e-01 6.2630452e-12
  1.1251955e-13 6.9682628e-11 5.8629644e-06 1.2054513e-13 2.3874591e-07
  1.1790163e-18 5.0249309e-08 1.0468316e-12]]
3
liger
The predicted Animal is a liger with accuracy =    0.9999939
